"""
配置模块
用于导入全局配置
"""
from config.settings import (
    CONFIG,
    DATA_DIR,
    HISTORY_CSV_DIR,
    HISTORY_PARQUET_DIR,
    METADATA_DIR,
    LOGS_DIR,
    CANONICAL_SCHEMA,
    CANONICAL_DTYPES,
    CSV_ENCODING,
    CSV_DATE_FORMAT,
    PARQUET_ENGINE,
    PARQUET_COMPRESSION,
    DEFAULT_DATA_SOURCE,
    DEFAULT_ADJUST,
    DEFAULT_START_DATE,
    CONCURRENT_WORKERS,
    BATCH_SIZE,
    MAX_RETRIES,
    RETRY_DELAY
)

# 别名，保持向后兼容
MAX_WORKERS = CONCURRENT_WORKERS
DATA_SOURCE_DEFAULT = DEFAULT_DATA_SOURCE
ADJUST_DEFAULT = DEFAULT_ADJUST

__all__ = [
    'CONFIG',
    'DATA_DIR',
    'HISTORY_CSV_DIR',
    'HISTORY_PARQUET_DIR',
    'METADATA_DIR',
    'LOGS_DIR',
    'CANONICAL_SCHEMA',
    'CANONICAL_DTYPES',
    'CSV_ENCODING',
    'CSV_DATE_FORMAT',
    'PARQUET_ENGINE',
    'PARQUET_COMPRESSION',
    'DEFAULT_DATA_SOURCE',
    'DEFAULT_ADJUST',
    'DEFAULT_START_DATE',
    'CONCURRENT_WORKERS',
    'BATCH_SIZE',
    'MAX_RETRIES',
    'RETRY_DELAY',
    # 别名
    'MAX_WORKERS',
    'DATA_SOURCE_DEFAULT',
    'ADJUST_DEFAULT'
]
